spring:
  application:
    name: nothingnessiseverywhere

  datasource:
    url: jdbc:mysql://localhost:3306/server?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root #数据库登录名
    password: 123456 #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true  # 开启热部署
      additional-paths: src/main # 重启目录
      exclude: application.yml

  mvc:
    view:
      prefix: /templates/error/
      suffix: .html
      static-path-pattern: /static/**



  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  content negotiation:
    media-types:webp=image/webp


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

server:
  tomcat:
    threads:
      max: 10
      min-spare: 1
    accept-count: 5

  servlet:
    session:
      timeout: 120s
  port:  8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: IiNCAIw=
    key-store-type: PKCS12
    key-alias: mydomain


